# Autograd with tensors

In [1]:
import torch

In [3]:
w = torch.randn(4,3)
w

tensor([[ 0.5202,  0.8705,  0.1557],
        [ 0.8372, -0.5560, -0.5787],
        [-0.6320,  0.4640,  0.4612],
        [ 1.5311,  0.2893,  0.9164]])

In [5]:
w.requires_grad_(True)

tensor([[ 0.5202,  0.8705,  0.1557],
        [ 0.8372, -0.5560, -0.5787],
        [-0.6320,  0.4640,  0.4612],
        [ 1.5311,  0.2893,  0.9164]], requires_grad=True)

In [6]:
y = torch.exp(w)
print(y)

tensor([[1.6824, 2.3882, 1.1685],
        [2.3100, 0.5735, 0.5606],
        [0.5315, 1.5904, 1.5860],
        [4.6233, 1.3354, 2.5003]], grad_fn=<ExpBackward0>)


In [7]:
print(y.grad_fn)

In [8]:
output = y.mean()
print(output)

tensor(1.7375, grad_fn=<MeanBackward0>)


In [9]:
print(w.grad)

None


In [10]:
output.backward()

In [11]:
print(w.grad)

tensor([[0.1402, 0.1990, 0.0974],
        [0.1925, 0.0478, 0.0467],
        [0.0443, 0.1325, 0.1322],
        [0.3853, 0.1113, 0.2084]])


In [12]:
print(output.requires_grad)

True


In [13]:
with torch.no_grad():
    output = (w+y).mean()

print(output.requires_grad)

False
